### ISSUE TITLE
'HCODE-pvt' is not in list

### ISSUE THREAD

**Issue by bossdm** [yashchandak/UnO#1]
Hi,

I am trying to use the run_Maze.py and run_Diabetes.py but when I do so I stumble on the error:

```
Traceback (most recent call last):
  File "/home/david/PycharmProjects/ImportanceSampling/UnO/Src/Utils/utils.py", line 246, in dynamic_load
    pos = abs_path.index('HCODE-pvt')
ValueError: 'HCODE-pvt' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/PycharmProjects/ImportanceSampling/UnO/Src/run_Maze.py", line 112, in <module>
    main(mode='train')
  File "/home/david/PycharmProjects/ImportanceSampling/UnO/Src/run_Maze.py", line 89, in main
    config = Config(args)
  File "/home/david/PycharmProjects/ImportanceSampling/UnO/Src/config.py", line 66, in __init__
    self.env, self.gym_env, self.cont_actions = self.get_domain(args.env_name, args=args, debug=args.debug,
  File "/home/david/PycharmProjects/ImportanceSampling/UnO/Src/config.py", line 98, in get_domain
    obj = utils.dynamic_load(path, tag, load_class=True)
  File "/home/david/PycharmProjects/ImportanceSampling/UnO/Src/Utils/utils.py", line 256, in dynamic_load
    raise ValueError("Failed to dynamically load the class: " + name )
ValueError: Failed to dynamically load the class: Maze
```

What is HCODE-pvt and how can i get it? Does this dynamic loading have anything to do with julia? Can I avoid using julia if I want? I did try to install julia but still got the error message.

**Comment by yashchandak** [comment]
Thanks for raising this. HCODE-pvt was the name of my project when it was under development, which got later renamed to UnO for the public release. 

Could you try replacing 'HCODE-pvt' with 'UnO' and see if that works? If it does not could you print(abs_path) before the error is raised and share the output of that?

(I am away from my work machine right now and will be able to push a fix only after a few days).


>> " Can I avoid using julia if I want?"

Only the data collection scripts are in python. The actual UnO code for the estimator/bounds is in Julia only.

**Comment by bossdm** [comment]
Hi,

I was able to solve the issue by replacing it with UnO and then using the commented line with "/" instead of "\\\\" (linux system vs windows I suppose).

I had a few more errors one of which is now resolved:
- a circular import
`from Src.Utils.Policy import Policy`

In the Src/Utils/Policy.py file. Removing this line solved the issue.

-'No such file or directory: UnO/Experiments_2/Maze/ActorCritic/DataDefault/0/Checkpoints/actor.pt'. Do I need to make this file before running the script? Or what can I do to prevent this error?

**Comment by yashchandak** [comment]
Thanks for pointing these out. Looks like once I had the data cached, I did not clean up the data collection files properly. I will update these soon.

> 'No such file or directory: UnO/Experiments_2/Maze/ActorCritic/DataDefault/0/Checkpoints/actor.pt'. 

In Src/config.py, if you change Line 37

> self.paths['Experiments'] = path.join(self.paths['root'], 'Experiments_2')

to

> self.paths['Experiments'] = path.join(self.paths['root'], 'Experiments')

I think that should fix the issue. But note that depending on the arguments of the code being executed, it might overwrite the data files in the Experiments folder. 

Alternatively, if you would want to create a new parallel set of experiments, then you could create a folder named 'Experiments_2' at the root, and then save the trained policies and collect the data accordingly.

THanks for your patience!

**Comment by bossdm** [comment]
Thanks, your suggestion for line 37 seems to work!
